name: cpr_vision310
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - opencv
  - pip:
      - mediapipe==0.10.9
      - streamlit==1.40.2
      - pytest==8.3.4
